Change cosmos sample from t1 to t2
Azure-Samples/azure-cosmos-db-documentdb-java-getting-started pull request #8
Opened 2020-11-12 07:17 UTC by Melanie-Ma

Change cosmos sample from track1 to track2.

@jongio, for notification.

2020-11-13 02:30 UTC, jongio commented
@conniey- Can you please review this?  Thanks

2020-11-19 01:17 UTC, helayoty requested changes
Thank you @Melanie-Ma for your PR. I've added a few comments.

2020-11-19 01:17 UTC, helayoty commented on pom.xml
> +      <version>4.5.0</version>
Would you please change the version to use the latest?

2020-11-19 01:17 UTC, helayoty commented on src/GetStarted/Program.java
> -    /**
Please undo the delete of the main function comment.

2020-11-19 02:17 UTC, kushagraThapar requested changes
The repo name is outdated. Also we already have samples for track 2 library here : https://github.com/Azure-Samples/azure-cosmos-java-sql-api-samples
I am not sure what is the purpose of these samples?

2020-11-19 02:40 UTC, jongio commented
@kushagraThapar - Would you like to make the call to delete this sample or remove the code and point to the replacement sample?

2020-11-19 02:45 UTC, kushagraThapar commented
@jongio - I am fine with both deleting / removing the code and pointing to the new sample. Ideally we should delete it, but I am fine keeping it as well (since the azure-documentdb SDK is still not deprecated) - but we should definitely remove the code from this sample, and point to the new samples.

2020-11-23 02:03 UTC, jongio commented
@kushagraThapar - Can you please provide a link to the sample you want to point to?  We'll update the readme with that link and then delete all the code here.  Thanks.

2020-11-23 17:22 UTC, kushagraThapar commented
@jongio - this is the getting-started guide we would like to point to - https://github.com/Azure-Samples/azure-cosmos-java-getting-started
Also, we can link the samples as well - https://github.com/Azure-Samples/azure-cosmos-java-sql-api-samples

2020-11-24 17:53 UTC, kushagraThapar approved these changes
LGTM, thanks!

2020-11-24 18:20 UTC, jongio approved these changes

2020-11-24 18:20 UTC, merged